apiVersion: v1
kind: ConfigMap
metadata:
  name: programmable-secrets-config
data:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: "55632c02cb971468424ae93c89366117"
  CIPHERTEXT_STORAGE_ROOT: /app/data/programmable-secrets
