apiVersion: v1
kind: Service
metadata:
  name: programmable-secrets
  labels:
    app: programmable-secrets
spec:
  selector:
    app: programmable-secrets
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
