apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: programmable-secrets-staging

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: registry.digitalocean.com/hashgraphonline/programmable-secrets-fe
    newTag: "staging"

patches:
  - path: namespace.delete.patch.yaml
